package com.huilan.eps.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2013-08-02T16:27:31.631+08:00
 * Generated source version: 2.5.10
 * 
 */
@WebService(targetNamespace = "http://service.webservice.eps.huilan.com/", name = "ArticleService")
@XmlSeeAlso({ObjectFactory.class})
public interface ArticleService {

    @WebResult(name = "article", targetNamespace = "")
    @RequestWrapper(localName = "getArticleByKey", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByKey")
    @WebMethod
    @ResponseWrapper(localName = "getArticleByKeyResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByKeyResponse")
    public com.huilan.eps.webservice.service.Article getArticleByKey(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "articleKey", targetNamespace = "")
        java.lang.String articleKey,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId
    );
    @WebResult(name = "article", targetNamespace = "")
    @RequestWrapper(localName = "getArticleByPage", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByPage")
    @WebMethod
    @ResponseWrapper(localName = "getArticleByPageResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByPageResponse")
    public com.huilan.eps.webservice.service.ArticlePage getArticleByPage(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "pageNo", targetNamespace = "")
        int pageNo,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "queryContent", targetNamespace = "")
        boolean queryContent,
        @WebParam(name = "parameter", targetNamespace = "")
        java.lang.Object parameter
    );
    @WebResult(name = "articleResult", targetNamespace = "")
    @RequestWrapper(localName = "addArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticle")
    @WebMethod
    @ResponseWrapper(localName = "addArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleResponse")
    public com.huilan.eps.webservice.service.Article addArticle(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "article", targetNamespace = "")
        com.huilan.eps.webservice.service.Article article
    );
    @WebResult(name = "articleResult", targetNamespace = "")
    @RequestWrapper(localName = "addArticleByAttachment", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleByAttachment")
    @WebMethod
    @ResponseWrapper(localName = "addArticleByAttachmentResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleByAttachmentResponse")
    public com.huilan.eps.webservice.service.Article addArticleByAttachment(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "articleFile", targetNamespace = "")
        com.huilan.eps.webservice.service.ArticleFile articleFile
    );
    @WebResult(name = "articleResult", targetNamespace = "")
    @RequestWrapper(localName = "updateArticleByAttachment", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleByAttachment")
    @WebMethod
    @ResponseWrapper(localName = "updateArticleByAttachmentResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleByAttachmentResponse")
    public com.huilan.eps.webservice.service.Article updateArticleByAttachment(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "articleFile", targetNamespace = "")
        com.huilan.eps.webservice.service.ArticleFile articleFile
    );
    @WebResult(name = "articleResult", targetNamespace = "")
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticle")
    @WebMethod
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleResponse")
    public com.huilan.eps.webservice.service.Article updateArticle(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "article", targetNamespace = "")
        com.huilan.eps.webservice.service.Article article,
        @WebParam(name = "pk", targetNamespace = "")
        java.lang.String pk,
        @WebParam(name = "pkValue", targetNamespace = "")
        java.lang.String pkValue
    );
    @WebResult(name = "articleResult", targetNamespace = "")
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.DeleteArticle")
    @WebMethod
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.DeleteArticleResponse")
    public com.huilan.eps.webservice.service.Article deleteArticle(
    		@WebParam(name = "loginProperty", targetNamespace = "")
            com.huilan.eps.webservice.service.LoginProperty loginProperty,
            @WebParam(name = "columnId", targetNamespace = "")
            java.lang.String columnId,
            @WebParam(name = "article", targetNamespace = "")
            com.huilan.eps.webservice.service.Article article,
            @WebParam(name = "pk", targetNamespace = "")
            java.lang.String pk,
            @WebParam(name = "pkValue", targetNamespace = "")
            java.lang.String pkValue
    );
}
