package com.huilan.eps.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-19T16:57:05.744+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://service.webservice.eps.huilan.com/", name = "ArticleService")
@XmlSeeAlso({ObjectFactory.class})
public interface ArticleService {

    @WebMethod
    @RequestWrapper(localName = "updateArticleByAttachment", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleByAttachment")
    @ResponseWrapper(localName = "updateArticleByAttachmentResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleByAttachmentResponse")
    @WebResult(name = "articleResult", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article updateArticleByAttachment(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "articleFile", targetNamespace = "")
        com.huilan.eps.webservice.service.ArticleFile articleFile
    );

    @WebMethod
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticle")
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.UpdateArticleResponse")
    @WebResult(name = "articleResult", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article updateArticle(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "article", targetNamespace = "")
        com.huilan.eps.webservice.service.Article article,
        @WebParam(name = "pk", targetNamespace = "")
        java.lang.String pk,
        @WebParam(name = "pkValue", targetNamespace = "")
        java.lang.String pkValue
    );

    @WebMethod
    @RequestWrapper(localName = "getArticleByKey", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByKey")
    @ResponseWrapper(localName = "getArticleByKeyResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByKeyResponse")
    @WebResult(name = "article", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article getArticleByKey(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "articleKey", targetNamespace = "")
        java.lang.String articleKey,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId
    );

    @WebMethod
    @RequestWrapper(localName = "addArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticle")
    @ResponseWrapper(localName = "addArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleResponse")
    @WebResult(name = "articleResult", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article addArticle(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "article", targetNamespace = "")
        com.huilan.eps.webservice.service.Article article
    );

    @WebMethod
    @RequestWrapper(localName = "addArticleByAttachment", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleByAttachment")
    @ResponseWrapper(localName = "addArticleByAttachmentResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.AddArticleByAttachmentResponse")
    @WebResult(name = "articleResult", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article addArticleByAttachment(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "articleFile", targetNamespace = "")
        com.huilan.eps.webservice.service.ArticleFile articleFile
    );

    @WebMethod
    @RequestWrapper(localName = "getArticleByPage", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByPage")
    @ResponseWrapper(localName = "getArticleByPageResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetArticleByPageResponse")
    @WebResult(name = "article", targetNamespace = "")
    public com.huilan.eps.webservice.service.ArticlePage getArticleByPage(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "pageNo", targetNamespace = "")
        int pageNo,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "queryContent", targetNamespace = "")
        boolean queryContent,
        @WebParam(name = "parameter", targetNamespace = "")
        java.lang.Object parameter
    );

    @WebMethod
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.DeleteArticle")
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.DeleteArticleResponse")
    @WebResult(name = "articleResult", targetNamespace = "")
    public com.huilan.eps.webservice.service.Article deleteArticle(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "columnId", targetNamespace = "")
        java.lang.String columnId,
        @WebParam(name = "article", targetNamespace = "")
        com.huilan.eps.webservice.service.Article article,
        @WebParam(name = "pk", targetNamespace = "")
        java.lang.String pk,
        @WebParam(name = "pkValue", targetNamespace = "")
        java.lang.String pkValue
    );
}
