package com.huilan.eps.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-18T15:45:45.615+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://service.webservice.eps.huilan.com/", name = "PageWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface PageWSService {

    @WebMethod
    @RequestWrapper(localName = "getPageTreeNode", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetPageTreeNode")
    @ResponseWrapper(localName = "getPageTreeNodeResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetPageTreeNodeResponse")
    @WebResult(name = "pages", targetNamespace = "")
    public java.util.List<com.huilan.eps.webservice.service.VoCommonPage> getPageTreeNode(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "parentId", targetNamespace = "")
        java.lang.String parentId,
        @WebParam(name = "siteId", targetNamespace = "")
        java.lang.String siteId,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );
}
