package com.huilan.eps.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-18T14:01:41.923+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://service.webservice.eps.huilan.com/", name = "SiteWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface SiteWSService {

    @WebMethod
    @RequestWrapper(localName = "getSiteByUser", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetSiteByUser")
    @ResponseWrapper(localName = "getSiteByUserResponse", targetNamespace = "http://service.webservice.eps.huilan.com/", className = "com.huilan.eps.webservice.service.GetSiteByUserResponse")
    @WebResult(name = "site", targetNamespace = "")
    public com.huilan.eps.webservice.service.SiteInfos getSiteByUser(
        @WebParam(name = "loginProperty", targetNamespace = "")
        com.huilan.eps.webservice.service.LoginProperty loginProperty,
        @WebParam(name = "parentId", targetNamespace = "")
        java.lang.String parentId
    );
}
