package com.huilan.eps.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.huilan.eps.webservice.service.SiteWSService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-18T14:01:41.967+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "SiteWSServiceImplService", 
                  wsdlLocation = "http://localhost:8080/eps/webservice/site?wsdl",
                  targetNamespace = "http://impl.service.webservice.eps.huilan.com/") 
public class SiteWSServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.webservice.eps.huilan.com/", "SiteWSServiceImplService");
    public final static QName SiteWSServiceImplPort = new QName("http://impl.service.webservice.eps.huilan.com/", "SiteWSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/eps/webservice/site?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SiteWSServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/eps/webservice/site?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SiteWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SiteWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiteWSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SiteWSServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SiteWSServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SiteWSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SiteWSService
     */
    @WebEndpoint(name = "SiteWSServiceImplPort")
    public SiteWSService getSiteWSServiceImplPort() {
        return super.getPort(SiteWSServiceImplPort, SiteWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteWSService
     */
    @WebEndpoint(name = "SiteWSServiceImplPort")
    public SiteWSService getSiteWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SiteWSServiceImplPort, SiteWSService.class, features);
    }

}
