package com.huilan.eps.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.huilan.eps.webservice.service.UserWSService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-19T15:07:29.420+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "UserWSServiceImplService", 
                  wsdlLocation = "http://localhost:7080/eps/webservice/user?wsdl",
                  targetNamespace = "http://impl.service.webservice.eps.huilan.com/") 
public class UserWSServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.webservice.eps.huilan.com/", "UserWSServiceImplService");
    public final static QName UserWSServiceImplPort = new QName("http://impl.service.webservice.eps.huilan.com/", "UserWSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/eps/webservice/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserWSServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/eps/webservice/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserWSServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserWSServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserWSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserWSService
     */
    @WebEndpoint(name = "UserWSServiceImplPort")
    public UserWSService getUserWSServiceImplPort() {
        return super.getPort(UserWSServiceImplPort, UserWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWSService
     */
    @WebEndpoint(name = "UserWSServiceImplPort")
    public UserWSService getUserWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserWSServiceImplPort, UserWSService.class, features);
    }

}
